add_newline = false
format = """$directory$git_branch$git_status$cmd_duration $character"""

[directory]
truncation_length = 3
style = "blue bold"

[git_branch]
symbol = "ğŸŒ± "
style = "green"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "yellow"

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
